on: [push]

jobs:
  fawltydeps:
    runs-on: ubuntu-latest
    name: "fawltydeps"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Run fawltydeps
        run: |
          fawltydeps
